### ISSUE TITLE
Getting "LDAPAttributeError" when abusing GenericAll from a parent group over a user

### ISSUE THREAD

**Issue by w0ltage** [ShutdownRepo/targetedKerberoast#10]
### Description
I have a user `damundsen` in a group `help desk level 1` with a parent group `information technology`, which gives all child groups `GenericAll` rights over the user `adunn`. This gives me the ability to add SPN to the user and kerberoast it.

When I try to use the tool to add SPN to user `adunn` and perform kerberoasting, I get the error `TypeError: argument of type 'LDAPAttributeError' is not iterable`.

I guess the problem in the nested membership, but I'm not sure about it.

### Full log

```
./targetedKerberoast.py -d "172.16.5.5" -u 'damundsen' -p 'pwned_by_ACLs!' -vv -D "INLANEFREIGHT" -U users.txt
[*] Starting kerberoast attacks
[*] Fetching usernames from file 
[!] argument of type 'LDAPAttributeError' is not iterable 
Traceback (most recent call last):
  File "/home/test/targetedKerberoast/./targetedKerberoast.py", line 274, in get_users_and_SPNs
    ldap_session.search(search_base=domain_dn, search_filter=search_filters, attributes=attributes, size_limit=100000)
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/core/connection.py", line 853, in search
    response = self.post_send_search(self.send('searchRequest', request, controls))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/strategy/sync.py", line 178, in post_send_search
    responses, result = self.get_response(message_id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/strategy/base.py", line 383, in get_response
    ref_response, ref_result = self.do_operation_on_referral(self._outstanding[message_id], responses[-2]['referrals'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/strategy/base.py", line 810, in do_operation_on_referral
    referral_connection.search(selected_referral['base'] or request['base'],
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/core/connection.py", line 838, in search
    request = search_operation(search_base,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/operation/search.py", line 371, in search_operation
    request['filter'] = compile_filter(parse_filter(search_filter, schema, auto_escape, auto_encode, validator, check_names).elements[0])  # parse the searchFilter string and compile it starting from the root node
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/operation/search.py", line 205, in parse_filter
    current_node.append(evaluate_match(search_filter[start_pos:end_pos], schema, auto_escape, auto_encode, validator, check_names))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/operation/search.py", line 165, in evaluate_match
    assertion = {'attr': left_part, 'value': validate_assertion_value(schema, left_part, right_part, auto_escape, auto_encode, validator, check_names)}
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/protocol/convert.py", line 159, in validate_assertion_value
    value = validate_attribute_value(schema, name, value, auto_encode, validator=validator, check_names=check_names)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/targetedKerberoast/env/lib/python3.11/site-packages/ldap3/protocol/convert.py", line 175, in validate_attribute_value
    raise LDAPAttributeError('invalid attribute ' + name)
ldap3.core.exceptions.LDAPAttributeError: invalid attribute ExtensibleMatch:
 matchingRule

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/test/targetedKerberoast/./targetedKerberoast.py", line 532, in main
    users = get_users_and_SPNs(ldap_session=ldap_session, domain=args.auth_domain, usernames= [line.strip() for line in f])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/test/targetedKerberoast/./targetedKerberoast.py", line 276, in get_users_and_SPNs
    if 'sizeLimitExceeded' in e:
       ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'LDAPAttributeError' is not iterable
```

Dependencies and their version

```
blinker==1.9.0
cffi==1.17.1
charset-normalizer==3.4.0
click==8.1.7
cryptography==42.0.8
dnspython==2.7.0
Flask==3.1.0
future==1.0.0
impacket==0.12.0
itsdangerous==2.2.0
Jinja2==3.1.4
ldap3==2.9.1
ldapdomaindump==0.9.4
markdown-it-py==3.0.0
MarkupSafe==3.0.2
mdurl==0.1.2
pyasn1==0.6.1
pyasn1_modules==0.4.1
pycparser==2.22
pycryptodome==3.21.0
pycryptodomex==3.21.0
Pygments==2.18.0
pyOpenSSL==24.0.0
rich==13.9.4
six==1.16.0
Werkzeug==3.1.3
```

**Comment by ShutdownRepo** [comment]
Hmm, no idea what it could be, leaving the issue open for anyone who'd bring insight on this

**Comment by squ4r00t** [comment]
Add the IP address of the DC in your host file like this:
```
172.16.5.5    DC DC.domain.local domain.local
```

Then run the command again, but provide the domain name (`-d domain.local`) instead of the IP
```bash
./targetedKerberoast.py -d domain.local -u 'damundsen' -p 'pwned_by_ACLs!' -vv -D "INLANEFREIGHT" -U users.txt
```

**Comment by theblackrussian** [comment]
For me the command below worked while experimenting on HTB machine _Administrator_.
Hope that's useful for whoever runs into that message.

`./targetedKerberoast.py -d administrator.htb -u 'emily' -p 'UXLCI5iE<SNIP>FKoHjXmb' -vv --dc-ip 10.10.11.42`
